In [3]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

## Tokenization: Breaking text into words and sentences

In [4]:
from nltk.tokenize import word_tokenize
text = "I am learning Natural Language Processing!"
word_tokenize(text)


['I', 'am', 'learning', 'Natural', 'Language', 'Processing', '!']

#### Stopwoeds Removal 

In [5]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [6]:
filtered_word = [w for w in word_tokenize(text) if w.lower() not in stop_words]

In [7]:
filtered_word

['learning', 'Natural', 'Language', 'Processing', '!']

## Text cleaner

In [8]:
import string
from nltk.corpus import  stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import  WordNetLemmatizer
import nltk

# Setup 
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
import string
from nltk.corpus import  stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import  WordNetLemmatizer
import nltk

# Setup 
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def clean_text(text):
    text = text.lower()
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    token = word_tokenize(text)
    
    stop_words = set(stopwords.words('english'))
    token = [word for word in token if word not in stop_words]
    
    # Lemmatizer 
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in token]
    
    return words
text = "I am learning Natural Language Processing!"

In [11]:
# Test
clean_text("The striped bats are hanging on their feet for best")

['striped', 'bat', 'hanging', 'foot', 'best']

#### Bag of words (BoW)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

In [15]:
docs = ['I love NLP', "NLP is fun!", "Fun with NLP and Python"]

In [16]:
x = vectorizer.fit_transform(docs)

In [18]:
print(vectorizer.get_feature_names_out())

['and' 'fun' 'is' 'love' 'nlp' 'python' 'with']


In [19]:
x.toarray()

array([[0, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 1]])

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(docs)


In [22]:
print(vectorizer.get_feature_names_out())
print(X.toarray())

['and' 'fun' 'is' 'love' 'nlp' 'python' 'with']
[[0.         0.         0.         0.861037   0.50854232 0.
  0.        ]
 [0.         0.54783215 0.72033345 0.         0.42544054 0.
  0.        ]
 [0.50461134 0.38376993 0.         0.         0.29803159 0.50461134
  0.50461134]]


In [23]:
vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')  # your own token pattern


In [27]:
v = vectorizer.fit_transform(docs)

In [28]:
print(vectorizer.get_feature_names_out())
print(x.toarray())

['and' 'fun' 'i' 'is' 'love' 'nlp' 'python' 'with']
[[0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0]
 [1 1 0 0 1 1 1]]


In [ ]:
import string
from nltk.corpus import  stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import  WordNetLemmatizer
import nltk

# Setup 
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def clean_text(text):
    text = text.lower()
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    token = word_tokenize(text)
    
    stop_words = set(stopwords.words('english'))
    token = [word for word in token if word not in stop_words]
    
    # Lemmatizer 
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in token]
    
    return words
text = "I am learning Natural Language Processing!"

def vectorizer(docs):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(docs)
    return vectorizer, X

# Original docs
docs = ['I love NLP', "NLP is fun!", "Fun with NLP and Python"]

# Clean the text and join tokens back into strings
for i in range(len(docs)):
    docs[i] = ' '.join(clean_text(docs[i]))

vectorizer, X = vectorizer(docs)
print(vectorizer.get_feature_names_out())
print(X.toarray())
print(X.toarray())

['fun' 'love' 'nlp' 'python']
[[0.         0.861037   0.50854232 0.        ]
 [0.78980693 0.         0.61335554 0.        ]
 [0.54783215 0.         0.42544054 0.72033345]]
[[0.         0.861037   0.50854232 0.        ]
 [0.78980693 0.         0.61335554 0.        ]
 [0.54783215 0.         0.42544054 0.72033345]]


In [33]:
docs = ['I love NLP', "NLP is fun!", "Fun with NLP and Python"]
for i in range(len(docs)):
    docs[i] = clean_text(docs[i])
print(docs)

[['love', 'nlp'], ['nlp', 'fun'], ['fun', 'nlp', 'python']]


In [31]:
docs = "I love you "
clean_text(docs)

['love']

### Top Phrases Extracor 

In [38]:
import string 
import nltk 
import pandas as pd 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer 
from sklearn.feature_extraction.text import TfidfVectorizer

# Setup
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/sanjaymahto/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [39]:
def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    token = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    token = [word for word in token if word not in stop_words]
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in token]
    return " ".join(words)

In [40]:
docs = [
    "I absolutely love machine learning and artificial intelligence!",
    "Natural language processing is a fascinating field of AI.",
    "I hate bugs in my code but I love debugging.",
    "Deep learning and neural networks are powerful tools."
]

# Clean the documents
cleaned_docs = [clean_text(doc) for doc in docs]


In [44]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(cleaned_docs)
feature_names = vectorizer.get_feature_names_out()


In [45]:
df = pd.DataFrame(X.toarray(), columns=feature_names)


In [47]:
def get_top_phrases_per_doc(tfidf, top_n=5):
    top_phrases = []
    for i, row in tfidf.iterrows():
        sorted_row = row.sort_values(ascending=False)
        top = sorted_row.head(top_n)
        top_phrases.append(list(zip(top.index, top.values)))
    return top_phrases
top_phrases = get_top_phrases_per_doc(df)

In [50]:
top_phrases

[[('absolutely', np.float64(0.3124514068609995)),
  ('machine learning', np.float64(0.3124514068609995)),
  ('absolutely love', np.float64(0.3124514068609995)),
  ('intelligence', np.float64(0.3124514068609995)),
  ('love machine', np.float64(0.3124514068609995))],
 [('language processing', np.float64(0.3015113445777636)),
  ('fascinating', np.float64(0.3015113445777636)),
  ('language', np.float64(0.3015113445777636)),
  ('natural', np.float64(0.3015113445777636)),
  ('field ai', np.float64(0.3015113445777636))],
 [('love debugging', np.float64(0.34056989045654285)),
  ('bug', np.float64(0.34056989045654285)),
  ('bug code', np.float64(0.34056989045654285)),
  ('code', np.float64(0.34056989045654285)),
  ('code love', np.float64(0.34056989045654285))],
 [('tool', np.float64(0.3068351989349343)),
  ('neural', np.float64(0.3068351989349343)),
  ('learning neural', np.float64(0.3068351989349343)),
  ('deep learning', np.float64(0.3068351989349343)),
  ('network', np.float64(0.30683519893

In [49]:
for i, phrases in enumerate(top_phrases):
    print(f"\nDocument {i+1} Top Phrases:")
    for phrase, score in phrases:
        print(f"  {phrase}: {score:.4f}")
    print()


Document 1 Top Phrases:
  absolutely: 0.3125
  machine learning: 0.3125
  absolutely love: 0.3125
  intelligence: 0.3125
  love machine: 0.3125


Document 2 Top Phrases:
  language processing: 0.3015
  fascinating: 0.3015
  language: 0.3015
  natural: 0.3015
  field ai: 0.3015


Document 3 Top Phrases:
  love debugging: 0.3406
  bug: 0.3406
  bug code: 0.3406
  code: 0.3406
  code love: 0.3406


Document 4 Top Phrases:
  tool: 0.3068
  neural: 0.3068
  learning neural: 0.3068
  deep learning: 0.3068
  network: 0.3068

